config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => {
    :omniauth_callbacks => "users/omniauth_callbacks",
    :registrations => 'users/registrations'
  }

  resources :users, only: [] do
    resource :profile, only: [:create, :new, :update, :edit, :show]
    resources :videos, only: [:create, :new, :update, :edit, :show, :index]
  end

  resources :topics do
    resources :posts, except: [:index]  # This 'resources :<controller> syntax generates RESTful CRUD routes to create, update, view, and delete Post instances.
  end


  get 'about' => 'welcome#about'  # Replaces "get 'welcome/about' to shorter URI of '/about' while maintaining the controller#action relationship"
  get 'faq' => 'welcome#faq'
  get 'why' => 'welcome#why'

  root to: "welcome#index"

end


# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/models/topic.rb
class Topic < ApplicationRecord
  has_many :posts, dependent: :destroy

  validates :name, length: { minimum: 5 }, presence: true
  validates :description, length: { minimum: 20 }, presence: true
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    @topics = Topic.all
  end

  def show
    @topic = Topic.find(params[:id])
  end

  def new
    @topic = Topic.new
  end

  def create
    @topic = Topic.new
    @topic.name = params[:topic][:name]
    @topic.description = params[:topic][:description]
    @topic.public = params[:topic][:public]

    if @topic.save
      redirect_to @topic, notice: "New Topic '#{@topic.name}' was saved successfully."
    else
      flash.now[:alert] = "Sorry, but it looks like we skipped a beat there... There was an error creating the new Topic. Please try again."
      render :new
    end
  end

  def edit
    @topic = Topic.find(params[:id])
  end

  def update
    @topic = Topic.find(params[:id])

    @topic.name = params[:topic][:name]
    @topic.description = params[:topic][:description]
    @topic.public = params[:topic][:public]

    if @topic.save
      flash[:notice] = "Topic update for '#{@topic.name}' was saved."
      redirect_to @topic
    else
      flash.now[:alert] = "Oops, it looks like we broke a string... There was an error updating the Topic. Please try again."
      render :edit
    end
  end

  def destroy
    @topic = Topic.find(params[:id])

    if @topic.destroy
      flash[:notice] = "\"#{@topic.name}\" was deleted successfully."
      redirect_to action: :index
    else
      flash.now[:alert] = "There was an error deleting the topic."
      render :show
    end
  end

end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/edit.html.erb
<h1>Edit Topic</h1>

<div class="row">
  <div class="col-md-4">
    <p>Guidelines for topics:</p>
    <ul>
      <li>Make sure it doesn't fall within the scope of an existing Topic</li>
      <li>Make sure it <em>does</em> fall within the Busker's Beat community scope</li>
      <li>Consider if there seems to be enough community interest to generate active participation, keeping the topic from growing stale</li>
      <ul>
        <li>Better to delay creating a topic until there is clearly a strong interest than to have to prune a slow topic later</li>
      </ul>
      <li>Make the Topic name and description define the intended use as clearly as possible</li>
      <li>Be ready to make a few posts to the new Topic right away to give members good examples of what the Topic is for</li>
    </ul>
  </div>
  <div class="col-md-8">
    <%= form_for @topic do |f| %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control', placeholder: "Enter new Topic name (at least 5 characters)" %>
      </div>
      <div class="form-group">
        <%= f.label :description %>
        <%= f.text_area :description, rows: 8, class: 'form-control', placeholder: "Enter new Topic description (at least 20 characters)" %>
      </div>
      <div class="form-group">
        <%= f.label :public, class: 'checkbox' do %>
          <%= f.check_box :public %> Public topic (uncheck for Private topics)
        <% end %>
      </div>
      <%= f.submit "Save Changes", class: 'btn btn-success' %>
    <% end %>
  </div>
</div>

app/views/topics/index.html.erb
<h1>Topics</h1>

<div class="row">
  <div class="col-md-8">
    <% @topics.each do |topic| %>
      <div class="media">
        <div class="media-body">
          <h4 class="media-heading">
            <%= link_to topic.name, topic %>
          </h4>
          <small>
            <%= topic.description %>
          </small>
        </div>
      </div>
    <% end %>
  </div>
  <div class = "col-md-4"><br />
    <%= link_to "Create a New Topic", new_topic_path, class: 'btn btn-success' %>
  </div>
</div>

app/views/topics/new.html.erb
<h1>Create a New Topic</h1>

<div class="row">
  <div class="col-md-4">
    <p>Guidelines for topics:</p>
    <ul>
      <li>Make sure it doesn't fall within the scope of an existing Topic</li>
      <li>Make sure it <em>does</em> fall within the Busker's Beat community scope</li>
      <li>Consider if there seems to be enough community interest to generate active participation, keeping the topic from growing stale</li>
      <ul>
        <li>Better to delay creating a topic until there is clearly a strong interest than to have to prune a slow topic later</li>
      </ul>
      <li>Make the Topic name and description define the intended use as clearly as possible</li>
      <li>Be ready to make a few posts to the new Topic right away to give members good examples of what the Topic is for</li>
    </ul>
  </div>
  <div class="col-md-8">
    <%= form_for @topic do |f| %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control', placeholder: "Enter new Topic name (at least 5 characters)" %>
      </div>
      <div class="form-group">
        <%= f.label :description %>
        <%= f.text_area :description, rows: 6, class: 'form-control', placeholder: "Enter new Topic description (at least 20 characters)" %>
      </div>
      <%= f.submit "Save", class: 'btn btn-success' %>
    <% end %>
  </div>
</div>

app/views/topics/show.html.erb
<h1><%= @topic.name %></h1>

<%= link_to "Edit Topic", edit_topic_path, class: 'btn btn-success' %>
<%= link_to "Delete Topic", @topic, method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete this Topic, along with any Posts and Comments it contains?' } %>

<div class="row">
  <div class="col-md-8">
    <p class="lead"><%= @topic.description %></p>
    <% @topic.posts.each do |post| %>
      <div class="media">
        <div class="media-body">
          <h4 class="media-heading">
            <%= link_to post.title, topic_post_path(@topic, post) %>
          </h4>
          <small>
            submitted <%= time_ago_in_words(post.created_at) %> ago <br>
            <%= post.comments.count %> Comments
          </small>
        </div>
      </div>
    <% end %>
  </div>
  <div class="col-md-4">
    <%= link_to "New Post", new_topic_post_path(@topic), class: 'btn btn-success' %>
  </div>
</div>