config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => {
    :omniauth_callbacks => "users/omniauth_callbacks",
    :registrations => 'users/registrations'
  }

  resources :users, only: [] do
    resource :profile, only: [:create, :new, :update, :edit, :show]
    resources :videos, only: [:create, :new, :update, :edit, :show, :index]
  end

  resources :topics do
    resources :posts, except: [:index]  # This 'resources :<controller> syntax generates RESTful CRUD routes to create, update, view, and delete Post instances.
  end


  get 'about' => 'welcome#about'  # Replaces "get 'welcome/about' to shorter URI of '/about' while maintaining the controller#action relationship"
  get 'faq' => 'welcome#faq'
  get 'why' => 'welcome#why'

  root to: "welcome#index"

end


# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/models/video.rb
class Video < ApplicationRecord
  belongs_to :user

#  YT_LINK_FORMAT = /\A.*(youtu.be\/|v\/|u\/\w\/|embed\/|watch\?v=|\&v=)([^#\&\?]*).*/i

  validates :uri, presence: true #, format: YT_LINK_FORMAT

end

app/controllers/videos_controller.rb
class VideosController < ApplicationController

  def index
    @videos = Video.order('created_at DESC')
  end

  def new
    @video = Video.new
  end

  def create
    @video = current_user.videos.new(video_params)
    if @video.save
      flash[:success] = 'Video added!'
      redirect_to user_profile_path(current_user)
    else
      flash.now[:alert] = "There was a problem creating the embedded video. Please try again."
      render :new
    end
  end

  def show
    @video = Video.all
  end


  private

  def video_params
    params.require(:video).permit(:uri)
  end

end

app/helpers/video_helper.rb
require 'youtube_embed'

  module VideoHelper

  def embed_video_for(url)
    video = YoutubeEmbed::Video.new(url)
    video.iframe
  end

end

app/views/videos/index.html.erb
<div class="jumbotron">
  <div class="container">
    <h1>Share your videos with the world!</h1>
    <p>Click the button below to share your video from YouTube.</p>
    <p>
      <%= link_to 'Add a video', new_user_video_path, class: 'btn btn-primary btn-lg' %>
    </p>
  </div>

  <h2>User Videos</h2>
  <% @videos.each do |video| %>
    <%= embed_video_for(video.uri) %>
  <% end %>
</div>

app/views/videos/new.html.erb
<div class="container">
  <h1>New video</h1>

  <div class="row">
    <div class="col-md-4">
      <%= form_for [current_user, @video] do |f| %>
        <%= render 'shared/errors', object: @video %>

        <div class="form-group">
          <%= f.label :uri %>
          <%= f.text_field :uri, class: 'form-control', required: true %>
          <span class="help-block">A link to the video on YouTube.</span>
        </div>

        <%= f.submit class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>

</div>