config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => {
    :omniauth_callbacks => "users/omniauth_callbacks",
    :registrations => 'users/registrations'
  }

  resources :users, only: [] do
    resource :profile, only: [:create, :new, :update, :edit, :show]
    resources :videos, only: [:create, :new, :update, :edit, :show, :index]
  end

  resources :topics do
    resources :posts, except: [:index]  # This 'resources :<controller> syntax generates RESTful CRUD routes to create, update, view, and delete Post instances.
  end


  get 'about' => 'welcome#about'  # Replaces "get 'welcome/about' to shorter URI of '/about' while maintaining the controller#action relationship"
  get 'faq' => 'welcome#faq'
  get 'why' => 'welcome#why'

  root to: "welcome#index"

end


# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Buskers Beat | Street Music</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

    <meta name="viewport" content="width=device-width, initial-scale=1">

  </head>

  <body>

    <!-- Facebook app setup -->
    <script>
      window.fbAsyncInit = function() {
        FB.init({
          appId      : '1277458452337879',
          xfbml      : true,
          version    : 'v2.8'
        });
        FB.AppEvents.logPageView();
      };

      (function(d, s, id){
         var js, fjs = d.getElementsByTagName(s)[0];
         if (d.getElementById(id)) {return;}
         js = d.createElement(s); js.id = id;
         js.src = "//connect.facebook.net/en_US/sdk.js";
         fjs.parentNode.insertBefore(js, fjs);
       }(document, 'script', 'facebook-jssdk'));
    </script>

    <div class="container">
      <ul class="nav nav-tabs" style="background-color: rgba(255, 255, 255, 0.9)">
        <li><%= link_to "Buskers Beat", root_path %></li>
        <li><%= link_to "Discussions", topics_path %></li>
        <li><%= link_to "About", about_path %></li>
        <li><%= link_to "FAQ", faq_path %></li>
        <% if user_signed_in? %>
          <% if current_user.profile.avatar.file? %>
            <li class='pull-right'><%= image_tag current_user.profile.avatar.url(:icon) %></li>
          <% end %>
          <li class='pull-right'><%= link_to 'Sign out', destroy_user_session_path, class: 'pull-right' %></li>
          <li class='pull-right'><div class="user-name"><strong><%= link_to current_user.name, "/users/#{current_user[:id]}/profile" %></strong></div></li>
        <% else %>
          <li class='pull-right'><%= link_to "Why register?", why_path %></li>
          <li class='pull-right'><%= link_to 'Register', new_user_registration_path, class: 'pull-right' %></li>
          <li class='pull-right'><%= link_to 'Sign In', new_user_session_path, class: 'pull-right' %></li>
        <% end %>
      </ul>

      <% if flash[:notice] %>
        <div class="alert alert-success">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:notice] %>
        </div>
      <% elsif flash[:alert] %>
        <div class="alert alert-warning">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:alert] %>
        </div>
      <% end %>

      <%= yield %>

    </div>

  </body>
</html>